version: '3.7'

services:
    shelter-helper-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: shelter-helper-app
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - shelter-helper-db
        environment:
            PHP_IDE_CONFIG: "serverName=shelter"
            XDEBUG_SESSION: docker-server
            SERVICE_NAME: shelter-helper-app
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./.env:/var/www/.env
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        #            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - app-network

    shelter-helper-webserver:
        image: nginx:alpine
        container_name: shelter-helper-webserver
        restart: unless-stopped
        tty: true
        depends_on:
            - shelter-helper-app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
        #            - ./nginx/ssl:/etc/nginx/ssl
        #            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        #            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - app-network

    shelter-helper-db:
        image: postgres:14-alpine
        container_name: shelter-helper-db
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - ./docker/pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_DB: shelter-helper
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            #POSTGRES_DB: ${DB_DATABASE}
            PGDATA: /var/lib/pgsql/data
        networks:
            - app-network


networks:
    app-network:
        driver: bridge

volumes:
    db-data:
        driver: local
